theme: jekyll-theme-slate
lang: ja-JP
title: Architect Elevator Blog日本語版
description: Real life writes the best stories, so ride the architect elevator up and down Enterprise IT with me. -- Gregor Hohpe
url: https://yyamano.github.io/architectelevator-ja/
google_analytics: UA-165722167-1
original:
  url: https://architectelevator.com/blog/
  author:
    name: Gregor Hohpe
    url: https://twitter.com/ghohpe
